import Foundation

class Fisherman: Fishing {
  
  var timeFishing: Double {
    Double(randomInteger(low: 3, high: 5))
  }
  
  // Fishing time generated by the fisherman to catch the fish
  var valueFishing: Double {
    // 100 / 500 = 0.2  0.2...1
    Double(randomFloat(low: 1, high: 10))
  }
  
  // Waiting time to fish again
  var waitTimeFishing: Double {
    Double(randomInteger(low: 0, high: 5))
  }
  
  var fish: Fish?
  var delegate: FishingDelegate?
  
}
